"""
Pydantic Models for CareerSim AI Project (Updated)

This file defines the data structures (schemas) for API requests/responses and
for function call tool interactions, ensuring strict data validation, clear
documentation, and type safety throughout the FastAPI application.
"""

from pydantic import BaseModel, EmailStr, Field, constr
from typing import List, Literal, Optional, Dict, Any, Union
from datetime import datetime
from enum import Enum
import uuid

# ========================================
# 1. USER & AUTHENTICATION MODELS
# (No changes from previous version)
# ========================================

class UserCreate(BaseModel):
    """Schema for new user registration."""
    username: str = Field(
        min_length=3,
        max_length=50,
        pattern=r"^[a-zA-Z0-9_-]+$",
        description="Unique username (alphanumeric, underscore, hyphen)"
    )
    password: str = Field(min_length=8, description="User's password (min 8 characters)")

class UserResponse(BaseModel):
    """Schema for returning user information."""
    id: int = Field(description="Unique user identifier from the database")
    username: str = Field(description="User's unique username")
    class Config: orm_mode = True

class Token(BaseModel):
    """Schema for the JWT access token response."""
    access_token: str = Field(description="The JWT access token")
    token_type: str = Field(default="bearer", description="The type of token")

class TokenData(BaseModel):
    """Internal schema for data decoded from a JWT."""
    username: Optional[str] = None


# ========================================
# 2. API ENDPOINT MODELS
# (Models used for direct communication with the Frontend via FastAPI endpoints)
# ========================================

class ScenarioRequest(BaseModel):
    """
    Request from frontend to generate a new simulation scenario.
    Matches the parameters for the `generate_career_scenario` function.
    """
    career_title: constr(
        strip_whitespace=True, to_lower=True, min_length=3, max_length=100
    ) = Field(description="The user-selected or typed career name")
    prompt_version: str = Field(
        default="v1",
        description="Version of the prompt template to use (default: v1)"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "career_title": "data analyst",
                "prompt_version": "v1.2"
            }
        }

class EvaluationRequest(BaseModel):
    """
    Request from frontend to evaluate a user's answer.
    Matches the parameters for the `evaluate_user_response` function.
    """
    career_title: constr(
        strip_whitespace=True, to_lower=True, min_length=3, max_length=100
    ) = Field(description="Career title related to the scenario")
    user_answer: constr(
        strip_whitespace=True, min_length=1, max_length=500
    ) = Field(description="User's answer text")
    session_id: uuid.UUID = Field(description="Unique session identifier (UUID)")
    task_mode: Literal["async", "sync"] = Field(
        default="async",
        description="Evaluation mode (async for background task)"
    )
    
    class Config:
        json_schema_extra = {
            "example": {
                "career_title": "software engineer",
                "user_answer": "Refactor the codebase to improve structure.",
                "session_id": "ad1e93c7-6fbb-46fa-8a3b-dcbb6f308a90",
                "task_mode": "async"
            }
        }


# ========================================
# 3. FUNCTION CALL ARGUMENT MODELS
# (Models to validate arguments generated by the LLM for function calling)
# ========================================

class GenerateScenarioArgs(BaseModel):
    """Arguments for the `generate_career_scenario` function tool."""
    career_title: constr(
        strip_whitespace=True, to_lower=True, min_length=3, max_length=100
    )
    prompt_version: str = "v1"

class EvaluateResponseArgs(BaseModel):
    """Arguments for the `evaluate_user_response` function tool."""
    career_title: constr(min_length=3, max_length=100)
    user_answer: constr(min_length=1, max_length=500)
    session_id: uuid.UUID
    task_mode: Literal["async", "sync"] = "async"

class GetTaskResultArgs(BaseModel):
    """Arguments for the `get_task_result` function tool."""
    task_id: uuid.UUID


# ========================================
# 4. FUNCTION CALL RESPONSE MODELS
# (Models for the structured data returned from our functions back to the LLM)
# ========================================

class FunctionStatusEnum(str, Enum):
    """Status of a function call execution."""
    SUCCESS = "success"
    PENDING = "pending"
    ERROR = "error"

class ErrorCodeEnum(str, Enum):
    """Standardized error codes from the function specification."""
    INVALID_INPUT = "INVALID_INPUT"
    UNAUTHORIZED = "UNAUTHORIZED"
    GENERATION_FAILED = "GENERATION_FAILED"
    EVALUATION_FAILED = "EVALUATION_FAILED"
    TASK_NOT_FOUND = "TASK_NOT_FOUND"
    RATE_LIMITED = "RATE_LIMITED"
    DATABASE_ERROR = "DATABASE_ERROR"

# --- Data Payloads for Successful Function Calls ---

class ScenarioData(BaseModel):
    """Successful data payload for `generate_career_scenario`."""
    career_title: str
    scenario: str
    options: List[str]

class EvaluationTaskData(BaseModel):
    """Successful data payload for `evaluate_user_response` (async)."""
    task_id: uuid.UUID
    message: str = "Evaluation task queued."

class EvaluationResultData(BaseModel):
    """Successful data payload for `get_task_result`."""
    feedback: str
    score: int = Field(ge=0, le=10)

# --- Generic Function Response Wrapper ---

class FunctionResponse(BaseModel):
    """
    A generic, standardized response wrapper for all function calls.
    This is the structure sent back to the LLM.
    """
    status: FunctionStatusEnum = Field(description="The execution status of the function call")
    data: Optional[Union[ScenarioData, EvaluationTaskData, EvaluationResultData, Dict[str, Any]]] = Field(
        default=None, description="The data payload on success or pending."
    )
    error_code: Optional[ErrorCodeEnum] = Field(
        default=None, description="A machine-readable error code if the status is 'error'."
    )
    error_message: Optional[str] = Field(
        default=None, description="A human-readable error message if the status is 'error'."
    )

    class Config:
        json_schema_extra = {
            "examples": [
                {
                    "summary": "Scenario Generation Success",
                    "value": {
                        "status": "success",
                        "data": {
                            "career_title": "software engineer",
                            "scenario": "You are leading a small dev team...",
                            "options": ["Refactor codebase", "Deploy hotfix"]
                        }
                    }
                },
                {
                    "summary": "Evaluation Task Queued",
                    "value": {
                        "status": "pending",
                        "data": {
                            "task_id": "8d9a32bf-76b3-4f9a-bc9d-2c77a46a8c3f",
                            "message": "Evaluation task queued."
                        }
                    }
                },
                {
                    "summary": "Get Task Result - Pending",
                    "value": {
                        "status": "pending",
                        "data": {}
                    }
                },
                {
                     "summary": "Get Task Result - Success",
                     "value": {
                        "status": "success",
                        "data": {
                            "feedback": "Your decision shows great leadership...",
                            "score": 9
                        }
                    }
                },
                {
                    "summary": "Function Error",
                    "value": {
                        "status": "error",
                        "data": None,
                        "error_code": "GENERATION_FAILED",
                        "error_message": "Unable to generate scenario for given title."
                    }
                }
            ]
        }


# ========================================
# USAGE EXAMPLES
# ========================================

if __name__ == "__main__":
    print("=" * 60)
    print("CAREERSIM PYDANTIC MODELS - USAGE EXAMPLES")
    print("=" * 60)

    # 1. Validating API request from Frontend (Section 2 model)
    print("\n1. Validating Frontend API Request for Evaluation:")
    frontend_payload = {
        "career_title": "software engineer",
        "user_answer": "I choose to refactor the code.",
        "session_id": "ad1e93c7-6fbb-46fa-8a3b-dcbb6f308a90",
        "task_mode": "async"
    }
    api_request = EvaluationRequest(**frontend_payload)
    print(f"✅ API Request Validated: {api_request.model_dump_json(indent=2)}")

    # 2. Validating arguments from an LLM function call (Section 3 model)
    print("\n2. Validating LLM-generated arguments:")
    llm_args = {
        "career_title": "software engineer",
        "user_answer": "I choose to refactor the code.",
        "session_id": "ad1e93c7-6fbb-46fa-8a3b-dcbb6f308a90"
        # 'task_mode' is omitted, will use default 'async'
    }
    validated_args = EvaluateResponseArgs(**llm_args)
    print(f"✅ LLM Arguments Validated: {validated_args.model_dump_json(indent=2)}")

    # 3. Constructing a successful function response for the LLM (Section 4 model)
    print("\n3. Constructing a successful Function Response:")
    func_response_payload = FunctionResponse(
        status=FunctionStatusEnum.SUCCESS,
        data=EvaluationResultData(
            feedback="Refactoring is a proactive choice that pays off long-term.",
            score=9
        )
    )
    print(f"✅ Function Response (Success): {func_response_payload.model_dump_json(indent=2)}")

    # 4. Constructing an error function response for the LLM (Section 4 model)
    print("\n4. Constructing an error Function Response:")
    error_response_payload = FunctionResponse(
        status=FunctionStatusEnum.ERROR,
        error_code=ErrorCodeEnum.TASK_NOT_FOUND,
        error_message="No task found with this ID."
    )
    print(f"✅ Function Response (Error): {error_response_payload.model_dump_json(indent=2)}")
    
    print("\n" + "=" * 60)
    print("✅ All examples completed successfully!")
    print("=" * 60)